development: 
  adapter: mysql
  database: tumblelog_dev
  host: localhost
  username: root 
  password:  

test:
  adapter: mysql
  database: tumblelog_test
  host: localhost
  username: root
  password:

production: 
  adapter: mysql
  database: tumblelog_production
  host: localhost
  username: root
  password: 
