# Your tumblelog's URL.  Make sure it ends with a /
url: http://ozimodo.rubyforge.org/

# The name of your tumblelog
name: your tumblelog

# how do you want your posts displayed on the main page?
# options are 'by date' or 'by post'
show: by date

# now, how many to show?
# if you picked 'by date' this is how many days to show -- note that today
#  counts as a day.
# if 'by post', then how many posts
limit: 7